development:
  adapter: postgresql 
  encoding: unicode
  database: hack_sesh_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql 
  encoding: unicode
  database: hack_sesh_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql 
  encoding: unicode
  database: hack_sesh_production
  pool: 5
  username:
  password:
